-- Teil O / 5 — Die Stimme und die Regeln des Begleiters. Pflegbar im Cockpit.
-- Register: buehne (Heft, poetisch, ≤ 2 Sätze, höchstens eine Frage) · betrieb (Studio, klar).
-- Platzhalter werden nur aus echten Daten gefüllt; fehlt einer, wird der Satz übersprungen (Ehrlichkeitsgesetz).

insert into public.begleiter_saetze (key, flaeche, kontext, welt, register, varianten, platzhalter, notiz) values
 ('heft.empfang.erster',      'heft','hero',  null,'buehne', '{"de":["Ich bin PAWN. Stöber in Ruhe — oder tipp mich an, dann zeige ich dir den Weg.","Willkommen. Drei Welten liegen vor dir. Ich bleibe in der Nähe."],"en":["I am PAWN. Browse in peace — or tap me and I will show you around.","Welcome. Three worlds ahead of you. I will stay close."]}', '{}', 'Erster Besuch, einmal'),
 ('heft.empfang.wieder',      'heft','hero',  null,'buehne', '{"de":["Willkommen zurück.","Schön, dass du wieder da bist."],"en":["Welcome back.","Good to see you again."]}', '{}', 'Wiederkehr ohne Merkliste'),
 ('heft.empfang.wieder_merk', 'heft','hero',  null,'buehne', '{"de":["Willkommen zurück. {werk} von {haus} ist noch da."],"en":["Welcome back. {werk} by {haus} is still here."]}', '{werk,haus}', 'Nur wenn das gemerkte Stück noch veröffentlicht ist'),
 ('heft.stillstand.hero',     'heft','hero',  null,'buehne', '{"de":["Mode, Interior, Kunst — welche zuerst?"],"en":["Fashion, interior, art — which first?"]}', '{}', 'Mit drei Chips'),
 ('heft.stillstand.stage',    'heft','stage', null,'buehne', '{"de":["Tipp ein Plus an — jedes Stück hat eine Geschichte."],"en":["Tap a plus — every piece has a story."]}', '{}', null),
 ('heft.welt.gewaehlt',       'heft','stage', null,'buehne', '{"de":["{welt}. Ich stelle dir hier immer wieder Neues auf."],"en":["{welt}. I will keep putting new pieces on this stage for you."]}', '{welt}', null),
 ('heft.verweilen.werk',      'heft','werk',  null,'buehne', '{"de":["{werk}: {material}, von {haus} aus {ort}."],"en":["{werk}: {material}, by {haus} from {ort}."]}', '{werk,material,haus,ort}', 'Nur mit allen vier Feldern'),
 ('heft.verweilen.bestellung','heft','werk',  null,'buehne', '{"de":["{werk} entsteht auf Bestellung — etwa {lead} Tage, dann ist es bei dir."],"en":["{werk} is made to order — about {lead} days, then it is yours."]}', '{werk,lead}', 'inventory_mode made_to_order + lead_time_days'),
 ('heft.merken.erstes',       'heft','werk',  null,'buehne', '{"de":["Gemerkt. Ein Stück sagt wenig — merk dir ein zweites, dann lese ich."],"en":["Noted. One piece says little — save a second and I will read."]}', '{}', null),
 ('heft.merken.zweites',      'heft','werk',  null,'buehne', '{"de":["Zwei Stücke. Soll ich lesen, was die beiden gemeinsam haben?"],"en":["Two pieces. Shall I read what they have in common?"]}', '{}', 'Angebot: Befund'),
 ('heft.merken.drittes',      'heft','werk',  null,'buehne', '{"de":["Drei gemerkt. Deine Linie wird deutlich — willst du sie sehen?"],"en":["Three saved. Your line is getting clear — want to see it?"]}', '{}', 'Führt zur DNA'),
 ('heft.haus.betreten',       'heft','haus',  null,'buehne', '{"de":["Das ist {haus}, Haus {nummer}. Zwei Seiten weiter steht das Atelier."],"en":["This is {haus}, house {nummer}. Two pages on, the atelier."]}', '{haus,nummer}', null),
 ('heft.quiz.fertig',         'heft','dna',   null,'buehne', '{"de":["Ich habe deine Linie. Ich glaube, ich kenne deinen Typ — sieh nach, ob ich recht habe."],"en":["I have your line. I think I know your type — see if I am right."]}', '{}', 'Führt zur Archetyp-Seite'),
 ('heft.archetyp.bestaetigt', 'heft','dna',   null,'buehne', '{"de":["Gut. Dann weiß ich, was ich dir aufstelle."],"en":["Good. Then I know what to put on stage for you."]}', '{}', null),
 ('heft.anprobe.angebot',     'heft','werk',  'mode','buehne', '{"de":["Willst du {werk} an dir sehen?"],"en":["Want to see {werk} on you?"]}', '{werk}', 'Nur mit aktivem Avatar'),
 ('heft.anprobe.ohne_avatar', 'heft','werk',  'mode','buehne', '{"de":["Ich kann dir zeigen, wie {werk} an dir aussieht. Dafür brauche ich einmal ein Foto von dir."],"en":["I can show you how {werk} looks on you. I need one photo of you for that."]}', '{werk}', 'Konto, kein Avatar — einmal überhaupt'),
 ('heft.anprobe.gast',        'heft','werk',  'mode','buehne', '{"de":["Mit einem Konto zeige ich dir {werk} an dir. Ein Foto, einmal."],"en":["With an account I can show you {werk} on you. One photo, once."]}', '{werk}', 'Gast — einmal je Sitzung'),
 ('heft.raum.angebot',        'heft','werk',  'interior','buehne', '{"de":["Willst du {werk} in deinem Raum sehen?"],"en":["Want to see {werk} in your room?"]}', '{werk}', null),
 ('heft.wand.angebot',        'heft','werk',  'kunst','buehne', '{"de":["Soll ich {werk} an deine Wand hängen? Ein Foto der Wand genügt."],"en":["Shall I hang {werk} on your wall? A photo of the wall is enough."]}', '{werk}', null),
 ('heft.anprobe.fertig',      'heft','werk',  null,'buehne', '{"de":["So sieht es aus. Passt es?"],"en":["This is how it looks. Does it fit?"]}', '{}', 'Chips: Passt / Eher nicht'),
 ('heft.suche.leer',          'heft','lesen', null,'buehne', '{"de":["Dazu habe ich nichts. Sag mir, was du suchst — anders."],"en":["Nothing for that. Tell me what you are looking for — differently."]}', '{}', 'Öffnet das Gespräch'),
 ('heft.hilfe',               'heft','lesen', null,'buehne', '{"de":["Suchst du etwas Bestimmtes? Sag es mir."],"en":["Looking for something specific? Tell me."]}', '{}', null),
 ('heft.kasse',               'heft','kasse', null,'buehne', '{"de":["Alles da? Ich bleibe, bis es durch ist."],"en":["All set? I will stay until it is through."]}', '{}', null),
 ('heft.kauf',                'heft','kasse', null,'buehne', '{"de":["Danke. {haus} erfährt es jetzt."],"en":["Thank you. {haus} hears about it now."]}', '{haus}', null),
 ('heft.rang.aufstieg',       'heft','dna',   null,'buehne', '{"de":["Ich weiß jetzt mehr über dich. Sieh mich an."],"en":["I know more about you now. Look at me."]}', '{}', 'Die Figur wechselt'),
 ('studio.vorschau.neu',      'studio','hub', null,'betrieb', '{"de":["Deine Doppelseite hat jetzt eine echte Vorschau — genau so, wie das Heft sie zeigt."],"en":["Your spread now has a real preview — exactly as the magazine shows it."]}', '{}', 'Einmal überhaupt'),
 ('studio.buehne.unter_drei', 'studio','heft',null,'betrieb', '{"de":["Auf deiner Bühne stehen {n} Werke. Ab drei kann ich sie veröffentlichen."],"en":["{n} works on your stage. From three on, I can publish it."]}', '{n}', null),
 ('studio.freistellen.angebot','studio','werk',null,'betrieb','{"de":["{werk} hat noch keinen Freisteller. Soll ich ihn machen? Ein Credit."],"en":["{werk} has no cut-out yet. Shall I make one? One credit."]}', '{werk}', null),
 ('studio.aufrufe',           'studio','hub', null,'betrieb', '{"de":["{n} Aufrufe für {werk} seit gestern."],"en":["{n} views for {werk} since yesterday."]}', '{n,werk}', 'Nur aus page_visits, nie geschätzt'),
 ('studio.anfrage.neu',       'studio','hub', null,'betrieb', '{"de":["Eine Anfrage zu {werk}. Sie wartet im Postfach."],"en":["An inquiry about {werk}. It is waiting in your inbox."]}', '{werk}', null)
on conflict (key) do nothing;

insert into public.begleiter_regeln (key, flaeche, ereignis, bedingung, satz_key, aktion, prioritaet, abklingzeit_s, einmal, notiz) values
 ('heft.empfang.erster',      'heft','betreten',      '{"besuch":"erster"}',                                   'heft.empfang.erster',      '{"art":"sagen"}', 100, 0,  'immer',   'Gast: einmal je Sitzung (Gerät)'),
 ('heft.empfang.wieder_merk', 'heft','betreten',      '{"besuch":"wieder","merkliste_min":1,"merk_sichtbar":true}', 'heft.empfang.wieder_merk','{"art":"sagen"}', 95, 0, 'sitzung', null),
 ('heft.empfang.wieder',      'heft','betreten',      '{"besuch":"wieder"}',                                   'heft.empfang.wieder',      '{"art":"sagen"}', 90,  0,  'sitzung', null),
 ('heft.stillstand.hero',     'heft','stillstand',    '{"kontext":"hero","min_ms":12000,"linie":false}',       'heft.stillstand.hero',     '{"art":"anbieten","chips":[{"text":"Mode","route":"/mode"},{"text":"Interior","route":"/interior"},{"text":"Kunst","route":"/kunst"}]}', 80, 0, 'sitzung', null),
 ('heft.stillstand.stage',    'heft','stillstand',    '{"kontext":"stage","min_ms":20000}',                    'heft.stillstand.stage',    '{"art":"sagen"}', 40,  90, 'sitzung', null),
 ('heft.welt.gewaehlt',       'heft','welt_gewaehlt', '{}',                                                    'heft.welt.gewaehlt',       '{"art":"sagen"}', 60,  30, 'sitzung', null),
 ('heft.verweilen.werk',      'heft','verweilen',     '{"min_ms":6000}',                                       'heft.verweilen.werk',      '{"art":"sagen"}', 50,  25, null,      'je Werk einmal je Sitzung (Schlüssel key#werk)'),
 ('heft.verweilen.bestellung','heft','verweilen',     '{"min_ms":6000,"bestellung":true}',                     'heft.verweilen.bestellung','{"art":"sagen"}', 52,  25, null,      'je Werk einmal'),
 ('heft.merken.erstes',       'heft','merken',        '{"merkliste_eq":1}',                                    'heft.merken.erstes',       '{"art":"sagen"}', 85,  0,  'sitzung', null),
 ('heft.merken.zweites',      'heft','merken',        '{"merkliste_eq":2}',                                    'heft.merken.zweites',      '{"art":"anbieten","funktion":"befund","chips":[{"text":"Ja, lies","funktion":"befund"},{"text":"Später","funktion":"weg"}]}', 88, 0, 'sitzung', null),
 ('heft.merken.drittes',      'heft','merken',        '{"merkliste_eq":3}',                                    'heft.merken.drittes',      '{"art":"fuehren","ziel":"/deine-dna"}', 88, 0, 'sitzung', null),
 ('heft.haus.betreten',       'heft','haus_betreten', '{}',                                                    'heft.haus.betreten',       '{"art":"sagen"}', 70,  20, null,      'je Haus einmal je Sitzung'),
 ('heft.quiz.fertig',         'heft','quiz_fertig',   '{}',                                                    'heft.quiz.fertig',         '{"art":"fuehren","ziel":"/deine-dna/archetyp"}', 90, 0, 'sitzung', null),
 ('heft.archetyp.bestaetigt', 'heft','archetyp_bestaetigt','{}',                                               'heft.archetyp.bestaetigt', '{"art":"sagen"}', 90,  0,  'sitzung', null),
 ('heft.anprobe.angebot',     'heft','verweilen',     '{"welt":"mode","avatar":true,"min_ms":4000}',           'heft.anprobe.angebot',     '{"art":"anbieten","funktion":"anprobe","chips":[{"text":"Ja, zeig es mir","funktion":"anprobe"},{"text":"Nicht jetzt","funktion":"weg"}]}', 75, 30, null, 'je Werk einmal'),
 ('heft.anprobe.ohne_avatar', 'heft','verweilen',     '{"welt":"mode","avatar":false,"konto":true,"min_ms":8000}', 'heft.anprobe.ohne_avatar','{"art":"fuehren","ziel":"/deine-dna/avatar"}', 65, 0, 'immer', null),
 ('heft.anprobe.gast',        'heft','verweilen',     '{"welt":"mode","konto":false,"min_ms":10000}',          'heft.anprobe.gast',        '{"art":"fuehren","ziel":"/konto"}', 40, 0, 'sitzung', null),
 ('heft.raum.angebot',        'heft','verweilen',     '{"welt":"interior","konto":true,"min_ms":6000}',        'heft.raum.angebot',        '{"art":"anbieten","funktion":"raum","chips":[{"text":"Ja","funktion":"raum"},{"text":"Nicht jetzt","funktion":"weg"}]}', 72, 30, null, 'je Werk einmal'),
 ('heft.wand.angebot',        'heft','verweilen',     '{"welt":"kunst","konto":true,"min_ms":6000}',           'heft.wand.angebot',        '{"art":"anbieten","funktion":"wand","chips":[{"text":"Ja","funktion":"wand"},{"text":"Nicht jetzt","funktion":"weg"}]}', 72, 30, null, 'je Werk einmal'),
 ('heft.anprobe.fertig',      'heft','anprobe_fertig','{}',                                                    'heft.anprobe.fertig',      '{"art":"anbieten","chips":[{"text":"Passt","funktion":"bewerten:passt"},{"text":"Eher nicht","funktion":"bewerten:nicht"}]}', 100, 0, null, null),
 ('heft.suche.leer',          'heft','suche_leer',    '{}',                                                    'heft.suche.leer',          '{"art":"oeffnen","ziel":"chat"}', 80, 60, null, null),
 ('heft.hilfe',               'heft','hilfe_gesucht', '{}',                                                    'heft.hilfe',               '{"art":"oeffnen","ziel":"chat"}', 60, 120, 'sitzung', 'z. B. 3 Richtungswechsel in 10 s'),
 ('heft.kasse',               'heft','kasse',         '{}',                                                    'heft.kasse',               '{"art":"sagen"}', 70,  0,  'sitzung', null),
 ('heft.kauf',                'heft','kauf',          '{}',                                                    'heft.kauf',                '{"art":"sagen"}', 100, 0,  null,      null),
 ('heft.rang.aufstieg',       'heft','rang_aufstieg', '{}',                                                    'heft.rang.aufstieg',       '{"art":"sagen"}', 95,  0,  null,      null),
 ('studio.vorschau.neu',      'studio','betreten',    '{}',                                                    'studio.vorschau.neu',      '{"art":"fuehren","ziel":"/studio/heft"}', 80, 0, 'immer', null),
 ('studio.buehne.unter_drei', 'studio','buehne_geoeffnet','{"stuecke_lt":3}',                                  'studio.buehne.unter_drei', '{"art":"sagen"}', 70,  60, null,      null),
 ('studio.freistellen.angebot','studio','werk_geoeffnet','{"cutout":false}',                                   'studio.freistellen.angebot','{"art":"anbieten","funktion":"freistellen"}', 65, 30, null, 'je Werk einmal'),
 ('studio.aufrufe',           'studio','betreten',    '{"aufrufe_min":3}',                                     'studio.aufrufe',           '{"art":"sagen"}', 60,  3600, null,     null),
 ('studio.anfrage.neu',       'studio','betreten',    '{"anfragen_offen_min":1}',                              'studio.anfrage.neu',       '{"art":"fuehren","ziel":"/studio/postfach"}', 85, 3600, null, null)
on conflict (key) do nothing;

